services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Klapaucius!123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend
    restart: always

  api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TRASKMANAGER;User Id=sa;Password=Klapaucius!123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - backend

volumes:
  sqlserver_data:

networks:
  backend:
